app/models/cheatsheet.py
from app.extensions import db

class Cheatsheet(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(150), nullable=False)
    content = db.Column(db.Text(3000), nullable=False)
    author = db.Column(db.String(150), nullable=False)
    public_access = db.Column(db.Boolean, default=False)
    def __repr__(self):
        return f'<Cheatsheet "{self.title}">'

app/cheatsheet/__init__.py
from flask import Blueprint

bp = Blueprint('cheatsheet', __name__)

from app.cheatsheet import routes

app/cheatsheet/routes.py
from flask import render_template, request, redirect, url_for, flash
from flask_login import login_required, current_user
from app.cheatsheet import bp
from app.extensions import db
from app.models.cheatsheet import Cheatsheet
from app.send_email.send_email import send_email
from app.articles.secure_filename import secure_filename

import os

@bp.route('/index')
@login_required
def index():
    cheatsheets = Cheatsheet.query.all()
    list_cheatsheets = []

    for cheatsheet in cheatsheets:       
        if current_user.username == cheatsheet.author or cheatsheet.public_access:
            id = cheatsheet.id
            title = cheatsheet.title
            
            path = url_for('static', filename=f'cheatsheets/{title}.txt')
            
            # edit button activity
            if current_user.username != cheatsheet.author:
                disabled = 'disabled'
            else:
                disabled = 'enabled'
            list_cheatsheets.append((id, title, path, disabled))

    return render_template('cheatsheet/index.html', cheatsheets=list_cheatsheets)



@bp.route('/edit_cheatsheet/<int:id>', methods=['GET', 'POST'])
@login_required
def edit_cheatsheet(id):
    cheatsheet = Cheatsheet.query.get_or_404(id)

    if request.method == 'POST':
        cheatsheet.title = request.form.get('title')
        cheatsheet.content = request.form.get('content')
        public_access = request.form.get('public_access')

        # preparation of information from the switch
        if public_access == 'on':
            cheatsheet.public_access = True
        else:
            cheatsheet.public_access = False

        if current_user.username != cheatsheet.author:
            flash("You have no permission to make changes!", 'flash_attention')
            return redirect(url_for('cheatsheet.edit_cheatsheet', id=cheatsheet.id))
        
        # making changes to the cheatsheet
        title = secure_filename(cheatsheet.title)
        content = cheatsheet.content
        filename = os.path.join('app', 'static', 'cheatsheets', f'{title}.txt')
        with open(filename, 'w', encoding='utf-8', newline='') as file_object:
            string = file_object.write(content)
        file_path = filename
        subject = f'Changes made to cheatsheet "{title}".'
        # send_email(file_path, subject)

        db.session.commit()

        flash("Your changes have been saved.", 'flash_success')
        return redirect(url_for('cheatsheet.edit_cheatsheet', id=cheatsheet.id))

    content = cheatsheet.content
    title = cheatsheet.title
    number = cheatsheet.id
    
    # setting switch depending on an entry in the database
    if cheatsheet.public_access:
        public_access = 'checked'
    else:
        public_access = ''

    return render_template('cheatsheet/edit_cheatsheet.html', content=content, title=title, id=number, public_access=public_access)


@bp.route('/add_cheatsheet', methods=['GET', 'POST'])
@login_required
def add_cheatsheet():
    if request.method == 'POST':
        title = request.form.get('title')
        content = request.form.get('content')
        public_access = request.form.get('public_access')
        author = current_user.username

        if public_access == 'on':
            public_access = True
        else:
            public_access = False

        title = f'{title} author {current_user.username}'
        title = secure_filename(title)

        title_exists = Cheatsheet.query.filter_by(title=title).first()
        if title_exists:
            flash("This cheatsheet already exists. Please choose a new title.", 'flash_attention')
            return redirect(url_for('cheatsheet.add_cheatsheet'))

        # make file .txt to send by email
        filename = os.path.join('app', 'static', 'cheatsheets', f'{title}.txt')
        with open(filename, 'w', encoding='utf-8', newline='') as file_object:
            string = file_object.write(content)
        file_path = filename
        subject = f'"{title}" cheatsheet has been added to the data store.'
        # send_email(file_path, subject)

        new_cheatsheet = Cheatsheet(title=title, content=content, author=author, public_access=public_access)
        db.session.add(new_cheatsheet)
        db.session.commit()

        flash('The cheatsheet added successfully.', 'flash_success')
        return redirect(url_for('cheatsheet.index'))

    return render_template('cheatsheet/add_cheatsheet.html')



@bp.route('/del_request/<int:id>')
@login_required
def del_request(id):
    cheatsheet = Cheatsheet.query.get_or_404(id)
    title=cheatsheet.title
    if current_user.username != cheatsheet.author:
        flash("You do not have permission to delete!!", 'flash_attention')
        return redirect(url_for('cheatsheet.index'))
    return render_template('cheatsheet/del_cheatsheet.html', title=title, id=id)

@bp.route('/del_cheatsheet/<int:id>')
@login_required
def del_cheatsheet(id):
    cheatsheet = Cheatsheet.query.get_or_404(id)
    title=cheatsheet.title

    # deleting a file from a folder
    path = os.path.join('app', 'static', 'cheatsheets', f'{title}.txt')
    if os.path.exists(path):
        os.remove(path)

    db.session.delete(cheatsheet)
    db.session.commit()

    flash(f'The cheatsheet { title } has been successfully deleted.', 'flash_success')
    return redirect(url_for('cheatsheet.index'))

app/templates/cheatsheet/add_cheatsheet.html
{% extends "base.html" %}

{% block content %}

<span class="fs-3">Adding an cheatsheet.</span>

<!-- {% with messages = get_flashed_messages() %}
{% if messages %}
<div class="flash_success">
    {{ messages[0] }}
</div>
{% endif %}
{% endwith %} -->

{% with messages = get_flashed_messages(with_categories=true) %}
{% for category, message in messages %}
<div class="{{ category }}">{{ message }}</div>
{% endfor %}
{% endwith %}

<form method="POST" action="{{url_for('cheatsheet.add_cheatsheet')}}" class="me-5">

  <div class="mb-3">
    <label for="exampleFormControlInput1" class="form-label">Title</label>
    <input type="text" name="title" class="form-control" id="exampleFormControlInput1"
      placeholder="Add a title to the cheatsheet" required>
  </div>
  <div class="mb-3">
    <label for="exampleFormControlTextarea1" class="form-label">Content</label>
    <textarea class="form-control" name="content" id="exampleFormControlTextarea1" rows="25" required></textarea>
  </div>
  <div class="row mb-3 ms-2">

      <div class="form-check form-switch">
        <input class="form-check-input" type="checkbox" role="switch" id="flexSwitchCheckChecked" name="public_access">
        <label class="form-check-label" for="flexSwitchCheckChecked">Allow public access</label>
      </div>
  
  </div>
  <button type="submit" class="btn btn-primary">Add</button>
</form>
{% endblock %}

app/templates/cheatsheet/del_cheatsheet.html
{% extends "base.html" %}

{% block content %}

<span class="fs-3">Are you sure about deleting the cheatsheet <span style="color:#0a73d6 ">{{ title }}</span>?</span>
<div class="p-2 col-auto">
        <a class="btn btn-danger mt-3" href="{{ url_for('cheatsheet.del_cheatsheet', id=id)}}" role="button">Delete
                cheatsheet !!!</a>
        <a class="btn btn-success mt-3 ms-2" href="{{ url_for('cheatsheet.index')}}" role="button">No, I changed my mind.</a>
</div>

{% endblock %}

app/templates/cheatsheet/edit_cheatsheet.html
{% extends "base.html" %}

{% block content %}

<span class="fs-3">View and edit cheat sheet.</span>

{% with messages = get_flashed_messages(with_categories=true) %}
{% for category, message in messages %}
<div class="{{ category }}">{{ message }}</div>
{% endfor %}
{% endwith %}

<form method="POST" action="" class="me-5">

  <div class="mb-3">
    <label for="exampleFormControlInput1" class="form-label">Title</label>
    <input type="text" name="title" class="form-control" value="{{ title }}" id="exampleFormControlInput1"
      placeholder="Add a title to the cheatsheet" required>
  </div>
  <div class="mb-3">
    <label for="exampleFormControlTextarea1" class="form-label">Content</label>
    <textarea class="form-control" name="content" id="exampleFormControlTextarea1" rows="25"
      required>{{ content }}</textarea>
  </div>
  <div class="form-check form-switch mb-3 ms-2">
    <input class="form-check-input" type="checkbox" role="switch" id="flexSwitchCheckChecked" name="public_access" {{
      public_access }}>
    <label class="form-check-label" for="flexSwitchCheckChecked">Allow public access</label>
  </div>
  <div class="d-flex justify-content-between">
    <button type="submit" class="btn btn-success">Save changes</button>
    <a class="btn btn-danger me-2" href="{{ url_for('cheatsheet.del_request', id=id)}}" role="button">Delete cheatsheet!!!</a>
  </div>

</form>
{% endblock %}

app/templates/cheatsheet/index.html
{% extends 'base.html' %}

{% block content %}
<div>
    <span class="fs-3">The cheatsheets:</span>
</div>

<!-- {% with messages = get_flashed_messages() %}
{% if messages %}
<div class="flash_success mb-3">
    {{ messages[0] }}
</div>
{% endif %}
{% endwith %} -->

{% with messages = get_flashed_messages(with_categories=true) %}
  {% for category, message in messages %}
    <div class="{{ category }}">{{ message }}</div>
  {% endfor %}
{% endwith %}

<div>
    {% for cheatsheet in cheatsheets %}
    <div class="fs-5">
      <a href="{{ cheatsheet[2] }}" class="link-secondary articles articles_a" target="_blank">{{ cheatsheet[1] }}</a>
      <a href="{{ url_for('cheatsheet.edit_cheatsheet', id=cheatsheet[0]) }}" role="button"
        class="btn btn-sm btn-outline-warning ms-3 {{ cheatsheet[3] }}">Edit</a>
    </div>
    {% endfor %}
</div>

{% endblock %}